var TwoLetterCountryCodeMap map[string]string = map[string]string{
	"Åland Islands":                        "AX",
	"Albania":                              "AL",
	"Algeria":                              "DZ",
	"American Samoa":                       "AS",
	"Andorra":                              "AD",
	"Angola":                               "AO",
	"Anguilla":                             "AI",
	"Antigua & Barbuda":                    "AG",
	"Argentina":                            "AR",
	"Armenia":                              "AM",
	"Aruba":                                "AW",
	"Australia":                            "AU",
	"Austria":                              "AT",
	"Azerbaijan":                           "AZ",
	"Bahamas":                              "BS",
	"Bahrain":                              "BH",
	"Bangladesh":                           "BD",
	"Barbados":                             "BB",
	"Belarus":                              "BY",
	"Belgium":                              "BE",
	"Belize":                               "BZ",
	"Benin":                                "BJ",
	"Bermuda":                              "BM",
	"Bhutan":                               "BT",
	"Bolivia":                              "BO",
	"Bonaire, St.Eustatius & Saba":         "BQ",
	"Bosnia & Herzegovina":                 "BA",
	"Botswana":                             "BW",
	"Brazil":                               "BR",
	"Brunei Darussalam":                    "BN",
	"Bulgaria":                             "BG",
	"Burkina Faso":                         "BF",
	"Burundi":                              "BI",
	"Cambodia":                             "KH",
	"Cameroon":                             "CM",
	"Canada":                               "CA",
	"Canary Island, Spain":                 "IC",
	"Cape Verde":                           "CV",
	"Cayman Islands":                       "KY",
	"Central African Republic":             "CF",
	"Chad":                                 "TD",
	"Chile":                                "CL",
	"China, People's Republic of":          "CN",
	"Colombia":                             "CO",
	"Comoros":                              "KM",
	"Congo":                                "CG",
	"Cook Islands":                         "CK",
	"Costa Rica":                           "CR",
	"Croatia":                              "HR",
	"Curaçao":                              "CW",
	"Cyprus":                               "CY",
	"Czech Republic":                       "CZ",
	"Denmark":                              "DK",
	"Djibouti":                             "DJ",
	"Dominica":                             "DM",
	"Dominican Republic":                   "DO",
	"Ecuador":                              "EC",
	"Egypt":                                "EG",
	"El Salvador":                          "SV",
	"Equatorial Guinea":                    "GQ",
	"Eritrea":                              "ER",
	"Estonia":                              "EE",
	"Ethiopia":                             "ET",
	"Falkland Islands (Malvinas)":          "FK",
	"Faroe Islands (Denmark)":              "FO",
	"Fiji":                                 "FJ",
	"Finland":                              "FI",
	"France":                               "FR",
	"French Guiana":                        "GF",
	"French Polynesia (Tahiti)":            "PF",
	"French Southern Territories":          "TF",
	"Gabon":                                "GA",
	"Gambia":                               "GM",
	"Georgia":                              "GE",
	"Germany":                              "DE",
	"Ghana":                                "GH",
	"Gibraltar":                            "GI",
	"Greece":                               "GR",
	"Greenland (Denmark)":                  "GL",
	"Grenada":                              "GD",
	"Guadeloupe":                           "GP",
	"Guam":                                 "GU",
	"Guatemala":                            "GT",
	"Guernsey":                             "GG",
	"Guinea":                               "GN",
	"Guinea-Bissau":                        "GW",
	"Guyana":                               "GY",
	"Haiti":                                "HT",
	"Heard Island and McDonald Islands":    "HM",
	"Honduras":                             "HN",
	"Hong Kong":                            "HK",
	"Hungary":                              "HU",
	"Iceland":                              "IS",
	"India":                                "IN",
	"Indonesia":                            "ID",
	"Iraq":                                 "IQ",
	"Ireland":                              "IE",
	"Isle of Man":                          "IM",
	"Israel":                               "IL",
	"Italy":                                "IT",
	"Ivory Coast":                          "CI",
	"Jamaica":                              "JM",
	"Japan":                                "JP",
	"Jersey":                               "JE",
	"Jordan":                               "JO",
	"Kazakhstan":                           "KZ",
	"Kenya":                                "KE",
	"Kiribati":                             "KI",
	"Korea, The Republic of":               "KR",
	"Kuwait":                               "KW",
	"Kyrgyzstan":                           "KG",
	"Laos":                                 "LA",
	"Latvia":                               "LV",
	"Lebanon":                              "LB",
	"Lesotho":                              "LS",
	"Liberia":                              "LR",
	"Liechtenstein":                        "LI",
	"Lithuania":                            "LT",
	"Luxembourg":                           "LU",
	"Macau":                                "MO",
	"Macedonia":                            "MK",
	"Madagascar":                           "MG",
	"Malawi":                               "MW",
	"Malaysia":                             "MY",
	"Maldives":                             "MV",
	"Mali":                                 "ML",
	"Malta":                                "MT",
	"Marshall Islands":                     "MH",
	"Martinique":                           "MQ",
	"Mauritania":                           "MR",
	"Mauritius":                            "MU",
	"Mayotte":                              "YT",
	"Mexico":                               "MX",
	"Micronesia, Federated States of":      "FM",
	"Moldova":                              "MD",
	"Monaco":                               "MC",
	"Mongolia":                             "MN",
	"Montenegro":                           "ME",
	"Montserrat":                           "MS",
	"Morocco":                              "MA",
	"Mozambique":                           "MZ",
	"Myanmar":                              "MM",
	"Namibia":                              "NA",
	"Nauru, Republic Of":                   "NR",
	"Nepal":                                "NP",
	"Netherlands":                          "NL",
	"New Caledonia":                        "NC",
	"New Zealand":                          "NZ",
	"Nicaragua":                            "NI",
	"Niger":                                "NE",
	"Nigeria":                              "NG",
	"Niue Island":                          "NU",
	"Norfolk Island":                       "NF",
	"Northern Mariana Islands":             "MP",
	"Norway":                               "NO",
	"Oman":                                 "OM",
	"Pakistan":                             "PK",
	"Palau":                                "PW",
	"Palestine":                            "PS",
	"Panama":                               "PA",
	"Papua New Guinea":                     "PG",
	"Paraguay":                             "PY",
	"Peru":                                 "PE",
	"Philippines":                          "PH",
	"Pitcairn":                             "PN",
	"Poland":                               "PL",
	"Portugal":                             "PT",
	"Puerto Rico":                          "PR",
	"Qatar":                                "QA",
	"Reunion":                              "RE",
	"Romania":                              "RO",
	"Russia":                               "RU",
	"Rwanda":                               "RW",
	"Saint Helena":                         "SH",
	"Saint Pierre and Miquelon":            "PM",
	"Samoa":                                "WS",
	"San Marino":                           "SM",
	"Sao Tome & Principe":                  "ST",
	"Saudi Arabia":                         "SA",
	"Senegal":                              "SN",
	"Serbia":                               "RS",
	"Seychelles":                           "SC",
	"Sierra Leone":                         "SL",
	"Singapore":                            "SG",
	"Slovakia":                             "SK",
	"Slovenia":                             "SI",
	"Solomon Islands":                      "SB",
	"South Africa":                         "ZA",
	"South Sudan":                          "SS",
	"Spain":                                "ES",
	"Sri Lanka":                            "LK",
	"St. Barthelemy":                       "BL",
	"St. Kitts and Nevis":                  "KN",
	"St. Lucia":                            "LC",
	"St. Maarten":                          "MF",
	"St. Vincent":                          "VC",
	"Sudan":                                "SD",
	"Suriname":                             "SR",
	"Svaldbard":                            "SJ",
	"Swaziland":                            "SZ",
	"Sweden":                               "SE",
	"Switzerland":                          "CH",
	"Taiwan":                               "TW",
	"Tajikistan":                           "TJ",
	"Tanzania":                             "TZ",
	"Thailand":                             "TH",
	"Timor-Leste":                          "TL",
	"Togo":                                 "TG",
	"Tokelau":                              "TK",
	"Tonga":                                "TO",
	"Trinidad and Tobago":                  "TT",
	"Tunisia":                              "TN",
	"Turkey":                               "TR",
	"Turkmenistan":                         "TM",
	"Turks and Caicos Islands":             "TC",
	"Tuvalu":                               "TV",
	"Uganda":                               "UG",
	"Ukraine":                              "UA",
	"United Arab Emirates":                 "AE",
	"United Kingdom":                       "GB",
	"United States":                        "US",
	"United States Minor Outlying Islands": "UM",
	"Uruguay":                              "UY",
	"Uzbekistan":                           "UZ",
	"Vanuatu":                              "VU",
	"Vatican City":                         "VA",
	"Venezuela":                            "VE",
	"Vietnam":                              "VN",
	"Virgin Islands (British)":             "VG",
	"Virgin Islands (U.S.)":                "VI",
	"Wallis and Futuna":                    "WF",
	"Western Sahara":                       "EH",
	"Yemen":                                "YE",
	"Zambia":                               "ZM",
	"Zimbabwe":                             "ZW",
}
